# Collaborative filtering for comprasion

In [ ]:
import import_ipynb
import import_data
import Arranging_data_for_comparison
import Similarity_method1
import Similarity_method2
import Similarity_method10
import IMP_Similarity_method10

import pandas as pd

In [2]:
N_RECOMMENDATIONS = 10 # Length of recommendation list
N_MOST_SIMILAR_SESSIONS = N_RECOMMENDATIONS #Option to filter the most similar sessions in Method2 
CSV_FILE_NAME = 'sessions_for_shaked.csv'#'data100000.csv'
REQUIRED_SIMILAR_SEARCHES = 4 #Number of similar searches to filter by
ALL_SIMILARITIES_CSV_FILE_NAME = 'all_similarities_df.csv'

 ## Import data

In [3]:
data= import_data.import_csv(CSV_FILE_NAME)
import_data.print_data_analysis(data)
all_sim_data_for_comparsion= import_data.import_csv(ALL_SIMILARITIES_CSV_FILE_NAME)

Number of users: 332393
Number of sessions: 611308

In [4]:
all_similarities_cities_lst_num= list(all_sim_data_for_comparsion.code1.unique())
all_similarities_cities_lst_str= list(map(str,all_similarities_cities_lst_num))

44

## Arranging the data

In [5]:
# Creating a DataFrame
data= Arranging_data_for_comparison.create_DataFrame_with_filt_cities(data,all_similarities_cities_lst_str)
#print(data['city'].unique().shape[0])
#remove all the cities that are not in all_similarities_data list
print(data['sessionId'].unique().shape[0])
filter_by_cities_in_all_similarities_data=data[data['city'].isin(all_similarities_cities_lst_str)]
# Filter sessions that have at least N searches of different cities
filter_sessions_N_dif_searches= Arranging_data_for_comparison.filter_sessions_N_dif_searches(filter_by_cities_in_all_similarities_data, REQUIRED_SIMILAR_SEARCHES)
#filter_sessions_N_dif_searches= Arranging_data_for_comparison.filter_sessions_N_dif_and_in_all_methods_searches(filter_by_cities_in_all_similarities_data, REQUIRED_SIMILAR_SEARCHES,all_similarities_cities_lst_num)
sessions_without_last= Arranging_data_for_comparison.sessions_without_last(filter_sessions_N_dif_searches)
sessions_with_only_last= Arranging_data_for_comparison.sessions_with_only_last(filter_sessions_N_dif_searches)
print(filter_sessions_N_dif_searches['sessionId'].unique().shape[0])
filter_sessions_N_dif_searches.head()

611308
10131

,userId,sessionId,unique_cityCodes,unique_cityCodes_filt,unique_cityCodes_filt2,nunique_cityCodes_filt2,city_searches,search_cnt,n_unique_cities,city,searches
6,0000acc7847448adb6125f421d47d41b,DEN02Bv64RM_iJkpSOT2hTzg,"1467, 139, 1085, 1843, 1045, 1839, 2067, 456, ...","[1467, 139, 456, 954, 954, 1467, 1467, 1004]","[1467, 139, 456, 954, 1004]",5,"(1004, 1)",1,17,1004,1
6,0000acc7847448adb6125f421d47d41b,DEN02Bv64RM_iJkpSOT2hTzg,"1467, 139, 1085, 1843, 1045, 1839, 2067, 456, ...","[1467, 139, 456, 954, 954, 1467, 1467, 1004]","[1467, 139, 456, 954, 1004]",5,"(954, 2)",4,17,954,2
6,0000acc7847448adb6125f421d47d41b,DEN02Bv64RM_iJkpSOT2hTzg,"1467, 139, 1085, 1843, 1045, 1839, 2067, 456, ...","[1467, 139, 456, 954, 954, 1467, 1467, 1004]","[1467, 139, 456, 954, 1004]",5,"(456, 1)",10,17,456,1
6,0000acc7847448adb6125f421d47d41b,DEN02Bv64RM_iJkpSOT2hTzg,"1467, 139, 1085, 1843, 1045, 1839, 2067, 456, ...","[1467, 139, 456, 954, 954, 1467, 1467, 1004]","[1467, 139, 456, 954, 1004]",5,"(139, 1)",16,17,139,1
6,0000acc7847448adb6125f421d47d41b,DEN02Bv64RM_iJkpSOT2hTzg,"1467, 139, 1085, 1843, 1045, 1839, 2067, 456, ...","[1467, 139, 456, 954, 954, 1467, 1467, 1004]","[1467, 139, 456, 954, 1004]",5,"(1467, 3)",17,17,1467,3

In [6]:
del data,filter_by_cities_in_all_similarities_data

In [ ]:
ff=filter_sessions_N_dif_searches.copy()
ff.drop_duplicates(subset=['sessionId'], keep='first')

### Transforming the data

<div>
<img src="img/fig_transforming_data.png" width="600"/>
</div>

In [8]:
utility_matrix=Arranging_data_for_comparison.transforming_data (sessions_without_last)
utility_matrix=Arranging_data_for_comparison.remove_unknown_sessions (utility_matrix,['#NAME?','#VALUE!'])
utility_matrix.head()

city,100,1004,101,1016,1025,1081,11237,1191,1193,1206,...,6174,638,663,6964,70,728,824,954,963,975
sessionId,,,,,,,,,,,,,,,,,,,,,
-0tlkIRXfdsdoPbeebnd7eEd,2,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
-1X0yQT3SiLOyRatqyaHisIb,0,0,0,0,0,0,0,0,2,0,...,0,0,0,0,0,0,0,0,2,0
-2XH6g9Bf27a5xB9Z0dLE-ZO,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,9,0,0,1,0,0
-2uri3H_IeJA12xf69POXII_,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,0
-33lCf8hjWLQGYyDIGxvrKhX,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,2,1,0

## Finding similarity

### Method 1: Similarity function A - Counting identical searches

<div>
<img src="img/sim_f_a.png" width="400"/>
</div>

In [9]:
def mehod1(utility_matrix_no_current_session, current_session_searches, n_recommendations):
    utility_matrix_Method_1=Similarity_method1.calc_similarity_method_1(utility_matrix_no_current_session,current_session_searches)
    utility_matrix_Method_1=Similarity_method1.filter_at_least_one_city_in_common(utility_matrix_Method_1)
    utility_matrix_Method_1=Similarity_method1.add_a_total_row(utility_matrix_Method_1)
    # Creating a sorted matrix of cities and the amount of their searches and get recommendations list
    sorted_recommendations_matrix_Method_1=Similarity_method1.get_sorted_city_searches_matrix(utility_matrix_Method_1)
    return Similarity_method1.get_top_X_recommendations_list(sorted_recommendations_matrix_Method_1 , n_recommendations)

### Method 2: Similarity function B

<div>
<img src="img/sim_f_b.png" width="500"/>
</div>

In [10]:
def mehod2(utility_matrix_no_current_session,current_session_searches, n_recommendations):
    utility_matrix_Method_2=Similarity_method2.calc_similarity_method_2(utility_matrix_no_current_session,current_session_searches)
    utility_matrix_Method_2=Similarity_method2.get_N_most_similar_sessions(utility_matrix_Method_2, N_MOST_SIMILAR_SESSIONS)
    #Recommendations list
    sorted_recommendations_matrix_Method_2=Similarity_method2.get_sorted_city_searches_matrix(utility_matrix_Method_2)
    return list(filter(None, sorted_recommendations_matrix_Method_2))[:n_recommendations]

# Call similarity methods for each session

In [ ]:
# Call for similarity Method 1 and similarity Method 2 and similarity Method 10 
def calc_similarity_for_specific_session(x , stable_utility_matrix, n_recommendations):
    session_id=list(x.reset_index())[1]
    unique_cityCodes_for_methods=ff.loc[(ff['sessionId']==session_id),'unique_cityCodes_filt2'].tolist()[0]
    rvrs_unique_cityCodes_for_methods=(unique_cityCodes_for_methods[:-1][::-1]) #Removing the last search and reversing the search order
    #print(session_id)
   
    n_x=x.loc[x!=0].to_dict()
    USE_sim,network_sim,hybrid_sim,image_sim= IMP_Similarity_method10.f_list_imp(all_sim_data_for_comparsion, rvrs_unique_cityCodes_for_methods, n_recommendations)
    myDict= {
        "searches" : unique_cityCodes_for_methods,
        "Recommendations_Method_1" : mehod1(stable_utility_matrix, n_x, n_recommendations),
        "Recommendations_Method_2" : mehod2(stable_utility_matrix, n_x, n_recommendations), 
        "Recommendations_USE_sim" : USE_sim,
        "Recommendations_network_sim" : network_sim,
        "Recommendations_hybrid_sim" : hybrid_sim,
        "Recommendations_image_sim" : image_sim

    }
    return myDict

# Find recommendations for all sessions
def calc_similarity_for_all_sessions(utility_matrix1, f_similarity_methods, stable_utility_matrix, n_recommendations):
    utility_matrix1['comp'] = utility_matrix1.apply(lambda x: f_similarity_methods(x, stable_utility_matrix, n_recommendations), axis=1)
    utility_matrix1=utility_matrix1.filter(['comp'], axis=1)  
    utility_matrix1= pd.DataFrame(utility_matrix1['comp'].values.tolist(), index=utility_matrix1.index) # Split the result into columns of the searches, method 1 recommendations, and method 2 recommendations
    return utility_matrix1

#Add columns of success in each of the methods
def get_index_from_recomendations_lst(x):
    lst_rec1=x['Recommendations_Method_1']
    lst_rec2=x['Recommendations_Method_2']
    lst_rec_USE_sim=x['Recommendations_USE_sim']
    lst_rec_network_sim=x['Recommendations_network_sim']
    lst_rec_hybrid_sim=x['Recommendations_hybrid_sim']
    lst_rec_image_sim=x['Recommendations_image_sim']
    l_search=x['Last_search']
    index_lst_rec1=0
    index_lst_rec2=0

    index_lst_rec_USE_sim=0
    index_lst_rec_network_sim=0
    index_lst_rec_hybrid_sim=0
    index_lst_rec_image_sim=0
    try:
        index_lst_rec1=lst_rec1.index(l_search)+1
    except ValueError: #if last search is not in N recomendations
        index_lst_rec1=0
    try:
        index_lst_rec2=lst_rec2.index(l_search)+1
    except ValueError: #if last search is not in N recomendations
        index_lst_rec2=0
    try:
        index_lst_rec_USE_sim=lst_rec_USE_sim.index(l_search)+1
    except ValueError: #if last search is not in N recomendations
        index_lst_rec_USE_sim=0
    try:
        index_lst_rec_network_sim=lst_rec_network_sim.index(l_search)+1
    except ValueError: #if last search is not in N recomendations
        index_lst_rec_network_sim=0
    try:
        index_lst_rec_hybrid_sim=lst_rec_hybrid_sim.index(l_search)+1
    except ValueError: #if last search is not in N recomendations
        index_lst_rec_hybrid_sim=0
    try:
        index_lst_rec_image_sim=lst_rec_image_sim.index(l_search)+1
    except ValueError: #if last search is not in N recomendations
        index_lst_rec_image_sim=0
    return index_lst_rec1, index_lst_rec2, index_lst_rec_USE_sim, index_lst_rec_network_sim, index_lst_rec_hybrid_sim, index_lst_rec_image_sim

#Deep_copy - For convenience - will change later
utility_matrix_with_recomendations= utility_matrix.copy()   
stable_utility_matrix= utility_matrix.copy() 


utility_matrix_with_recomendations=calc_similarity_for_all_sessions(utility_matrix, calc_similarity_for_specific_session, stable_utility_matrix, N_RECOMMENDATIONS)

#Add last search
last_search=sessions_with_only_last.set_index('sessionId').filter(['city'], axis=1).rename(columns = {'city':'Last_search'})
fnl= pd.merge(utility_matrix_with_recomendations, last_search, right_index=True, left_index=True)

#Add columns of success in each of the methods : 0= no matches between the last search an the N recommenadion , 1= the Last_search is the first recomedation
fnl_with_success=fnl.copy() #Deep_copy - For convenience - will change later     

del fnl,last_search,utility_matrix_with_recomendations,stable_utility_matrix

fnl_with_success['Success_M1'],fnl_with_success['Success_M2'],fnl_with_success['Success_USE'],fnl_with_success['Success_network'],fnl_with_success['Success_hybrid'],fnl_with_success['Success_image']  = zip(*fnl_with_success.apply(lambda x: get_index_from_recomendations_lst(x), axis=1))
fnl_with_success

# Analysis of results

In [12]:
success_Method1=fnl_with_success['Success_M1'].value_counts().sort_index()
success_Method2=fnl_with_success['Success_M2'].value_counts().sort_index()
success_Method_USE=fnl_with_success['Success_USE'].value_counts().sort_index()
success_Method_network=fnl_with_success['Success_network'].value_counts().sort_index()
success_Method_hybrid=fnl_with_success['Success_hybrid'].value_counts().sort_index()
success_Method_image=fnl_with_success['Success_image'].value_counts().sort_index()

result= pd.concat([success_Method1, success_Method2,success_Method_USE,success_Method_network,success_Method_hybrid,success_Method_image], axis=1, join="outer").fillna(0).astype(int)

print("The times the last search did not appear in the N recommendations in either method:")
print(len(fnl_with_success.loc[(fnl_with_success['Success_M1']==0)&(fnl_with_success['Success_M2']==0)&(fnl_with_success['Success_USE']==0)&(fnl_with_success['Success_network']==0)&(fnl_with_success['Success_hybrid']==0)&(fnl_with_success['Success_image']==0)]))

result

The times the last search did not appear in the N recommendations in either method:
299

,Success_M1,Success_M2,Success_USE,Success_network,Success_hybrid,Success_image
0,1066,4223,4294,1509,1699,4163
1,1187,317,150,1255,1078,370
2,1041,511,213,1072,992,247
3,819,232,243,861,855,209
4,683,99,321,635,628,323
5,531,86,261,465,450,320
6,462,105,316,334,315,199
7,307,143,340,233,187,261
8,301,249,217,139,177,228
9,277,414,257,95,172,277
10,164,459,226,240,285,241